#!/usr/bin/env python3
"""
generate_kotlin.py — Generate Kotlin source files from event-spec.yaml.

Usage:
    python generate_kotlin.py \\
        --spec docs/analytics/event-spec.yaml \\
        --src app/src/main/java \\
        --templates .claude/skills/firebase-events-impl/assets/kotlin_templates \\
        [--dry-run] [--no-confirm] [--with-helpers]

Output files (all under <src>/<package>/event/ with header `// AUTO-GENERATED`):
    ScreenName.kt
    ButtonName.kt
    PopupName.kt                (if popups[] non-empty)
    ClickBtnEv.kt               (Lint interface)
    AnalyticsEventsUtils.kt
    BaseTrackedActivity.kt      (view_binding | hybrid)
    BaseTrackedFragment.kt      (view_binding | hybrid)
    TrackedComposables.kt       (compose | hybrid)
    <CustomEvent>.kt            (one per custom_events[].name)

Idempotency:
    Every file starts with a marker including SHA256 of spec content. Running
    twice with same spec yields zero diff.

Exit codes:
    0 — Success
    1 — Validation error (re-runs validate_spec.py)
    2 — IO error
"""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import yaml
    from jinja2 import Environment, FileSystemLoader, StrictUndefined
except ImportError:
    sys.stderr.write(
        "ERROR: PyYAML+Jinja2 missing.  "
        "pip install -r .claude/skills/firebase-events-impl/scripts/requirements.txt\n"
    )
    sys.exit(2)


GEN_MARKER_PREFIX = "// AUTO-GENERATED by firebase-events-impl skill from event-spec.yaml."
GEN_MARKER_HASH = "// Spec-hash: "


# ============================================================================
# Main
# ============================================================================

def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Kotlin from event-spec.yaml")
    ap.add_argument("--spec", required=True, help="Path to event-spec.yaml")
    ap.add_argument("--src", required=True, help="Path to app/src/main/java")
    ap.add_argument("--templates", required=True, help="Path to kotlin_templates/")
    ap.add_argument(
        "--dry-run", action="store_true",
        help="Print which files would change, don't write"
    )
    ap.add_argument(
        "--no-confirm", action="store_true",
        help="Skip diff confirmation, overwrite directly (CI mode)"
    )
    ap.add_argument(
        "--with-helpers", action="store_true",
        help="Always emit BaseTrackedActivity/Fragment & TrackedComposables regardless of usage"
    )
    args = ap.parse_args()

    spec_path = Path(args.spec).resolve()
    src_path = Path(args.src).resolve()
    tpl_path = Path(args.templates).resolve()

    if not spec_path.is_file():
        sys.stderr.write(f"ERROR: spec not found: {spec_path}\n")
        return 2
    if not src_path.is_dir():
        sys.stderr.write(f"ERROR: src dir not found: {src_path}\n")
        return 2
    if not tpl_path.is_dir():
        sys.stderr.write(f"ERROR: templates dir not found: {tpl_path}\n")
        return 2

    # Validate first
    validator = Path(__file__).parent / "validate_spec.py"
    if validator.exists():
        rc = subprocess.run(
            [sys.executable, str(validator), str(spec_path)],
            check=False,
        ).returncode
        if rc != 0:
            sys.stderr.write("\nABORTED: spec validation failed.\n")
            return 1

    spec = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    spec_hash = _normalize_and_hash(spec)
    print(f"\n→ Spec hash: {spec_hash[:12]}")

    ctx = _build_context(spec)
    project_pkg = ctx["package"]
    event_pkg = f"{project_pkg}.event"
    out_dir = src_path / Path(*event_pkg.split("."))
    out_dir.mkdir(parents=True, exist_ok=True)

    env = Environment(
        loader=FileSystemLoader(str(tpl_path)),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["camel"] = _camel
    env.filters["pascal"] = _pascal
    env.filters["upper_snake"] = _upper_snake

    files_to_render = _decide_files(ctx, args)
    changes: List[tuple] = []  # (path, content, action)

    for tpl_name, out_name in files_to_render:
        out_path = out_dir / out_name
        rendered = _render(env, tpl_name, ctx, spec_hash)

        if out_path.exists():
            current = out_path.read_text(encoding="utf-8")
            if current.strip() == rendered.strip():
                changes.append((out_path, rendered, "unchanged"))
                continue
            if not _is_generated(current):
                changes.append((out_path, rendered, "drift-overwrite"))
            else:
                changes.append((out_path, rendered, "update"))
        else:
            changes.append((out_path, rendered, "create"))

    # Custom events (1 file each)
    for ev in ctx["custom_events"]:
        out_name = f"{_pascal(ev['name'])}.kt"
        out_path = out_dir / out_name
        rendered = _render_custom_event(env, ev, ctx, spec_hash)
        if out_path.exists():
            current = out_path.read_text(encoding="utf-8")
            if current.strip() == rendered.strip():
                changes.append((out_path, rendered, "unchanged"))
                continue
            if not _is_generated(current):
                changes.append((out_path, rendered, "drift-overwrite"))
            else:
                changes.append((out_path, rendered, "update"))
        else:
            changes.append((out_path, rendered, "create"))

    # Per-screen ClickBtnEv enums (NAMING_CONVENTION.md: 1 enum per screen).
    # Sinh 1 file `<ScreenPascal>BtnEv.kt` cho mỗi screen có buttons.
    for screen_block in ctx["screen_button_blocks"]:
        out_name = f"{screen_block['class_name']}.kt"
        out_path = out_dir / out_name
        rendered = _render_screen_btn_ev(env, screen_block, ctx, spec_hash)
        if out_path.exists():
            current = out_path.read_text(encoding="utf-8")
            if current.strip() == rendered.strip():
                changes.append((out_path, rendered, "unchanged"))
                continue
            if not _is_generated(current):
                changes.append((out_path, rendered, "drift-overwrite"))
            else:
                changes.append((out_path, rendered, "update"))
        else:
            changes.append((out_path, rendered, "create"))

    # Summary
    counts = {"create": 0, "update": 0, "unchanged": 0, "drift-overwrite": 0}
    for _, _, action in changes:
        counts[action] += 1

    print(f"\n→ Plan: {counts['create']} create, {counts['update']} update, "
          f"{counts['unchanged']} unchanged, {counts['drift-overwrite']} drift-overwrite\n")

    for p, _, a in changes:
        rel = p.relative_to(src_path.parent.parent) if src_path.parent.parent in p.parents else p
        if a == "unchanged":
            print(f"  · {rel}")
        elif a == "create":
            print(f"  + {rel}")
        elif a == "update":
            print(f"  ~ {rel}")
        elif a == "drift-overwrite":
            print(f"  ! {rel}  (file modified outside generator — will be OVERWRITTEN)")

    if args.dry_run:
        print("\n(dry-run — no files written)")
        return 0

    if counts["create"] + counts["update"] + counts["drift-overwrite"] == 0:
        print("\n✓ All files up-to-date.")
        return 0

    if not args.no_confirm:
        ans = input("\nApply changes? [y/N] ").strip().lower()
        if ans not in ("y", "yes"):
            print("Aborted.")
            return 0

    for p, content, action in changes:
        if action == "unchanged":
            continue
        p.write_text(content, encoding="utf-8")
    print("\n✓ Done.")
    return 0


# ============================================================================
# Context builder
# ============================================================================

def _build_context(spec: Dict[str, Any]) -> Dict[str, Any]:
    project = spec.get("project") or {}
    features = project.get("features") or {}
    mode = project.get("mode", "view_binding")
    event_name_style = project.get("event_name_style", "pascal_case")
    if event_name_style not in ("pascal_case", "camel_case"):
        raise ValueError(
            f"Invalid project.event_name_style: {event_name_style!r}. "
            f"Must be 'pascal_case' or 'camel_case'."
        )

    screens = spec.get("screens") or []
    for s in screens:
        s.setdefault("kind", _infer_kind(s.get("class", "")))
        s.setdefault("parent", None)
        s.setdefault("class", "")

    popups = spec.get("popups") or []
    for p in popups:
        p.setdefault("class", "")

    buttons = _expand_buttons(spec.get("buttons") or [])
    screen_button_blocks = _build_screen_button_blocks(buttons, screens, popups)

    # ignore_screens — class names that AppExitTracker should NOT attribute
    # (vd splash/ad activities). INTEGRATION.md Step 5.
    ignore_screens_raw = project.get("ignore_screens") or []
    if not isinstance(ignore_screens_raw, list):
        ignore_screens_raw = []
    ignore_class_names = set()
    for item in ignore_screens_raw:
        if isinstance(item, str):
            # Could be screen id (lookup class) or raw class name
            screen_by_id = {s["id"]: s for s in screens}
            if item in screen_by_id:
                ignore_class_names.add(screen_by_id[item]["class"])
            else:
                ignore_class_names.add(item)
        elif isinstance(item, dict) and "class" in item:
            ignore_class_names.add(item["class"])

    # screen_name_map for AnalyticsBootstrap.resolveScreenName() lambda.
    # Build from spec screens (class → const) + ignore_screens entries.
    screen_name_map: List[Dict[str, Any]] = []
    seen_classes = set()
    for s in screens:
        cls = s.get("class", "").strip()
        if not cls or cls in seen_classes:
            continue
        seen_classes.add(cls)
        screen_name_map.append({
            "class_name": cls,
            "screen_const": _upper_snake(s["id"]),
            "ignore": cls in ignore_class_names,
        })
    # Add ignored classes not in screens list (vd SplashActivity, AdActivity)
    for cls in ignore_class_names:
        if cls in seen_classes:
            continue
        seen_classes.add(cls)
        screen_name_map.append({
            "class_name": cls,
            "screen_const": "",
            "ignore": True,
        })
    custom_events = spec.get("custom_events") or []
    for ev in custom_events:
        ev.setdefault("description", "")
        ev.setdefault("params", [])
        ev.setdefault("trigger_hint", None)
        for p in ev.get("params") or []:
            p.setdefault("type", "string")
            p.setdefault("enum", None)
    user_properties = spec.get("user_properties") or []
    for up in user_properties:
        up.setdefault("type", "string")
        up.setdefault("enum", None)
        up.setdefault("description", "")

    ctx = {
        "project_name": project.get("name", ""),
        "package": project.get("package", "").strip("."),
        "application_class": project.get("application_class", ""),
        "version": project.get("version", "1.0.0"),
        "mode": mode,
        "event_name_style": event_name_style,
        "is_view_binding": mode in ("view_binding", "hybrid"),
        "is_compose": mode in ("compose", "hybrid"),
        "is_hybrid": mode == "hybrid",
        "features": {
            "iap": bool(features.get("iap")),
            "ads": bool(features.get("ads")),
            "rate_dialog": bool(features.get("rate_dialog")),
            "open_app_from": bool(features.get("open_app_from")),
            "onboarding": bool(features.get("onboarding")),
            "appsflyer": bool(features.get("appsflyer")),
            "permissions": features.get("permissions") or [],
        },
        "screens": screens,
        "popups": popups,
        "buttons": buttons,
        "screen_button_blocks": screen_button_blocks,
        "screen_name_map": screen_name_map,
        "custom_events": custom_events,
        "user_properties": user_properties,
    }
    return ctx


def _build_screen_button_blocks(
    buttons: List[Dict[str, Any]],
    screens: List[Dict[str, Any]],
    popups: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Group buttons by screen → 1 enum class per screen (NAMING_CONVENTION.md).

    Cross-screen constraint: same `id` MUST have same `name` & `variants`.

    Each block has:
        screen           : dict (from spec)
        screen_const     : str (HOME — uppercase form of screen id)
        class_name       : str (HomeBtnEv — PascalCase of screen id + 'BtnEv')
        entries          : list of {const_name, button_name, popup_const, description}
        buttons_in_popups: int
    """
    # Verify cross-screen consistency: same id → same name & variants
    by_id: Dict[str, Dict[str, Any]] = {}
    for b in buttons:
        bid = b["id"]
        if bid not in by_id:
            by_id[bid] = b
        else:
            existing = by_id[bid]
            if existing.get("name") != b.get("name"):
                raise ValueError(
                    f"Button id `{bid}` has conflicting names across screens: "
                    f"`{existing.get('name')}` vs `{b.get('name')}`. "
                    f"Same id MUST have same name."
                )
            if existing.get("variants") != b.get("variants"):
                raise ValueError(
                    f"Button id `{bid}` has conflicting types/variants. "
                    f"Same id MUST have same type."
                )

    # Group by screen
    by_screen: Dict[str, List[Dict[str, Any]]] = {}
    for b in buttons:
        screen_id = b.get("screen", "")
        if not screen_id:
            continue
        by_screen.setdefault(screen_id, []).append(b)

    blocks: List[Dict[str, Any]] = []
    for screen in screens:
        sid = screen["id"]
        if sid not in by_screen:
            continue
        screen_const = _upper_snake(sid)
        class_name = _pascal(sid) + "BtnEv"
        entries: List[Dict[str, Any]] = []
        buttons_in_popups = 0
        for b in by_screen[sid]:
            popup_id = b.get("popup")
            popup_const = _upper_snake(popup_id) if popup_id else ""
            popup_part = f"_{popup_const}" if popup_const else ""
            for v in b["variants"]:
                # Entry name: {SCREEN}[_{POPUP}]_{ACTION}{VARIANT_SUFFIX}
                # ACTION derived from button.name (camelCase value, lint-validated)
                action_const = _upper_snake(b["name"])
                const_name = f"{screen_const}{popup_part}_{action_const}{v['const_suffix']}"
                button_name_value = b["name"] + (v.get("name_suffix", "") or "")
                desc_parts = [f"`{b['name']}`"]
                if v.get("raw_state"):
                    desc_parts.append(f"state={v['raw_state']}")
                if popup_id:
                    desc_parts.append(f"popup={popup_id}")
                description = ", ".join(desc_parts)
                entries.append({
                    "const_name": const_name,
                    "button_name": button_name_value,
                    "popup_const": popup_const,
                    "description": description,
                })
                if popup_id:
                    buttons_in_popups += 1
        blocks.append({
            "screen": screen,
            "screen_const": screen_const,
            "class_name": class_name,
            "entries": entries,
            "buttons_in_popups": buttons_in_popups,
        })
    return blocks


def _render_screen_btn_ev(env, block: Dict[str, Any], ctx: Dict[str, Any], spec_hash: str) -> str:
    """Render one ScreenBtnEv.kt file for a given screen block."""
    tpl = env.get_template("ScreenBtnEv.kt.jinja")
    rendered = tpl.render(
        package=ctx["package"],
        project_name=ctx["project_name"],
        version=ctx["version"],
        spec_hash=spec_hash,
        screen=block["screen"],
        screen_const=block["screen_const"],
        class_name=block["class_name"],
        entries=block["entries"],
        buttons_in_popups=block["buttons_in_popups"],
    )
    header = (
        f"// AUTO-GENERATED — DO NOT EDIT.\n"
        f"// Source: docs/analytics/event-spec.yaml (hash={spec_hash[:12]})\n"
        f"// Regenerate: /analytics-generate\n\n"
    )
    return header + rendered


def _expand_buttons(buttons: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Expand stateful buttons (toggle/checkbox/accordion/radio) into variants.

    Each entry gets `variants`: list of {const_suffix, name_suffix, raw_state}.
    For plain buttons, variants = [{const_suffix: "", name_suffix: "", raw_state: None}].
    """
    expanded = []
    for b in buttons:
        btype = b.get("type")
        if btype == "toggle":
            variants = [
                {"const_suffix": "_ON", "name_suffix": "On", "raw_state": "on"},
                {"const_suffix": "_OFF", "name_suffix": "Off", "raw_state": "off"},
            ]
        elif btype == "checkbox":
            variants = [
                {"const_suffix": "_CHECKED", "name_suffix": "Checked", "raw_state": "checked"},
                {"const_suffix": "_UNCHECKED", "name_suffix": "Unchecked", "raw_state": "unchecked"},
            ]
        elif btype == "accordion":
            variants = [
                {"const_suffix": "_EXPANDED", "name_suffix": "Expanded", "raw_state": "expanded"},
                {"const_suffix": "_COLLAPSED", "name_suffix": "Collapsed", "raw_state": "collapsed"},
            ]
        elif btype == "radio":
            variants = []
            for opt in b.get("options") or []:
                lbl = opt["label"]
                variants.append({
                    "const_suffix": "_" + _upper_snake(lbl),
                    "name_suffix": lbl,
                    "raw_state": opt["value"],
                })
        else:
            variants = [{"const_suffix": "", "name_suffix": "", "raw_state": None}]
        nb = dict(b)
        nb["variants"] = variants
        # Ensure optional keys always exist so Jinja StrictUndefined doesn't crash
        nb.setdefault("popup", None)
        nb.setdefault("type", None)
        nb.setdefault("triggers", [])
        nb.setdefault("options", [])
        expanded.append(nb)
    return expanded


def _infer_kind(cls: str) -> str:
    if cls.endswith("Activity"):
        return "activity"
    if cls.endswith("Fragment"):
        return "fragment"
    if cls.endswith("Screen") or cls.endswith("Page") or cls.endswith("Route"):
        return "composable"
    return "activity"


# ============================================================================
# Decide which files to render
# ============================================================================

def _decide_files(ctx: Dict[str, Any], args) -> List[tuple]:
    files = [
        ("ClickBtnEv.kt.jinja", "ClickBtnEv.kt"),
        ("ScreenName.kt.jinja", "ScreenName.kt"),
        # ButtonName.kt REMOVED — per NAMING_CONVENTION.md, button values inline
        # trong per-screen enum entries (vd `HOME_BACK(ScreenName.HOME, "back", "")`).
        # KHÔNG còn `object ButtonName { const val BTN_X = "x" }`.
        ("AnalyticsEventsUtils.kt.jinja", "AnalyticsEventsUtils.kt"),
        ("AnalyticsBootstrap.kt.jinja", "AnalyticsBootstrap.kt"),
    ]
    if ctx["popups"] or args.with_helpers:
        files.append(("PopupName.kt.jinja", "PopupName.kt"))
    if ctx["is_view_binding"] or args.with_helpers:
        files.append(("BaseTrackedActivity.kt.jinja", "BaseTrackedActivity.kt"))
        files.append(("BaseTrackedFragment.kt.jinja", "BaseTrackedFragment.kt"))
    # Dialog tracking helpers — generate khi có popup trong spec (cả compose + view_binding
    # đều dùng được; Compose dialog có thể dùng TrackedPopup thay thế nhưng class này phục
    # vụ trường hợp dialog không nằm trong @Composable scope).
    if ctx["popups"] or args.with_helpers:
        files.append(("BaseTrackedDialog.kt.jinja", "BaseTrackedDialog.kt"))
        if ctx["is_view_binding"] or ctx["is_hybrid"] or args.with_helpers:
            files.append(("TrackedDialogBuilder.kt.jinja", "TrackedDialogBuilder.kt"))
    if ctx["is_compose"] or args.with_helpers:
        files.append(("TrackedComposables.kt.jinja", "TrackedComposables.kt"))
    return files


# ============================================================================
# Rendering helpers
# ============================================================================

def _render(env, tpl: str, ctx: Dict[str, Any], spec_hash: str) -> str:
    template = env.get_template(tpl)
    rendered = template.render(spec_hash=spec_hash, **ctx)
    return _ensure_marker(rendered, spec_hash)


def _render_custom_event(env, ev: Dict[str, Any], ctx: Dict[str, Any], spec_hash: str) -> str:
    template = env.get_template("CustomEvent.kt.jinja")
    rendered = template.render(event=ev, spec_hash=spec_hash, **ctx)
    return _ensure_marker(rendered, spec_hash)


def _ensure_marker(content: str, spec_hash: str) -> str:
    if GEN_MARKER_PREFIX in content[:300]:
        return content
    header = (
        f"{GEN_MARKER_PREFIX}\n"
        f"// DO NOT EDIT — run /analytics-generate to update.\n"
        f"{GEN_MARKER_HASH}{spec_hash}\n\n"
    )
    return header + content


def _is_generated(content: str) -> bool:
    return GEN_MARKER_PREFIX in content[:400]


def _normalize_and_hash(spec: Any) -> str:
    canon = yaml.safe_dump(spec, default_flow_style=False, sort_keys=True)
    return hashlib.sha256(canon.encode("utf-8")).hexdigest()


# ============================================================================
# String helpers (used as Jinja filters)
# ============================================================================

_SNAKE_TO_CAMEL = re.compile(r"_([a-z0-9])")


def _camel(s: Any) -> str:
    """home_settings → homeSettings"""
    s = str(s) if s is not None else ""
    if not s:
        return ""
    return _SNAKE_TO_CAMEL.sub(lambda m: m.group(1).upper(), s)


def _pascal(s: Any) -> str:
    """home_settings → HomeSettings"""
    c = _camel(s)
    return c[:1].upper() + c[1:] if c else ""


def _upper_snake(s: Any) -> str:
    """HomeSettings → HOME_SETTINGS  |  home_settings → HOME_SETTINGS"""
    s = str(s) if s is not None else ""
    if not s:
        return ""
    if "_" in s:
        return s.upper()
    res = re.sub(r"([A-Z]+)", r"_\1", s).upper().lstrip("_")
    # Make sure leading digits get a separator-free form (e.g. "5Min" -> "5MIN")
    return res or s.upper()


if __name__ == "__main__":
    sys.exit(main())
